#
# Copyright (c) 2020-2021 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

name: Next Dockerimage

on:
  push:
    branches: [ main ]
  repository_dispatch:
    types: [build]

jobs:
  dispatch:
    strategy:
      matrix:
        repo: ['johnmcollier/registry-test-workflow']
    runs-on: ubuntu-latest
    steps:
      - name: Get the repository name and commit sha
        id: get_commit_info
        run: |
          if [ -z ${{ github.event.client_payload.repo }} ];
          then
            echo ::set-output name=repo::$(echo ${{ github.event.repository.name }})
          else
            echo ::set-output name=repo::$(echo ${{ github.event.client_payload.repo }})
          fi

          if [ -z ${{ github.event.client_payload.sha }} ];
          then
            echo ::set-output name=sha::$(echo ${{ github.sha }})
          else
            echo ::set-output name=sha::$(echo ${{ github.event.client_payload.sha }})
          fi
          
      - name: Get the repository name and commit sha
        run: ${{ steps.get_commit_info.outputs.REPO }}
        
      - name: Repository dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: build
          client-payload: '{"repo": "${{ steps.get_commit_info.outputs.REPO }}", "sha": "${{ steps.get_commit_info.outputs.SHA }}"}'
